# modules/desktop/greeter.nix — the login screen, built in Quickshell.
#
# Replaces regreet when `claude-os.greeter.enable` is on. The runtime shape is
# structurally identical to what it replaces — only the process inside the
# kiosk changes:
#
#   before:  greetd -> cage -> regreet     (GTK4)
#   after:   greetd -> cage -> quickshell  (QML, Quickshell.Services.Greetd)
#
# greetd stays, cage stays, the PAM stack stays. See
# docs/plans/2026-08-15-quickshell-greeter-plan.md for why this rather than
# qmlgreet (unpackaged, MauiKit-dependent, and explicitly unsupported outside
# Nitrux) — and note that plan's phase 0 resolved NEGATIVE: regreet is not slow
# (greetd is ready in ~1s). The case for this is visual consistency with the bar
# plus removing the session-picker footgun, NOT performance.
#
# RING 1 (declarative) — this is boot/security-posture surface, so Nix owns it
# and the repo is truth. No ring-2 mutable state is introduced.
{
  lib,
  config,
  pkgs,
  user,
  ...
}:
let
  cfg = config.claude-os.greeter;
  themeLib = import ../../lib/theme.nix;

  # The SAME generator the bar uses. This is the whole point: the login screen
  # reads the identical singleton, so it cannot drift from the session's theme.
  themeQml = import ../../lib/quickshell-theme.nix {
    colors = config.lib.stylix.colors;
    inherit themeLib;
  };

  # Sessions offered at the greeter, as argv the greetd protocol can launch.
  #
  # ONLY the UWSM entry is offered, deliberately. The plain `hyprland.desktop`
  # never activates graphical-session.target, which strands hyprpaper, hypridle
  # and gammastep — no wallpaper, no idle-lock, no night light (observed at the
  # first post-inversion login, 2026-07-12). regreet listed both and the only
  # defence was Tom remembering which to pick; here the wrong option simply does
  # not exist. That footgun removal is a main reason this module exists.
  #
  # argv mirrors hyprland-uwsm.desktop's Exec line:
  #   uwsm start -e -D Hyprland hyprland.desktop
  sessions = [
    {
      name = "Hyprland (UWSM)";
      command = [
        "${config.programs.uwsm.package}/bin/uwsm"
        "start"
        "-e"
        "-D"
        "Hyprland"
        "hyprland.desktop"
      ];
    }
  ];

  greeterConfigQml = ''
    pragma Singleton
    import Quickshell
    import QtQuick

    // GENERATED by modules/desktop/greeter.nix. Edit the .nix, never this file.
    Singleton {
      readonly property string user: ${builtins.toJSON user}
      readonly property string wallpaper: ${builtins.toJSON "file://${config.stylix.image}"}
      readonly property var sessions: (${builtins.toJSON sessions})
    }
  '';

  greeterQml =
    pkgs.runCommand "claudeos-greeter-qml"
      {
        inherit themeQml greeterConfigQml;
      }
      ''
        mkdir -p "$out"
        cp ${./greeter}/shell.qml "$out/"
        printf '%s' "$themeQml" > "$out/Theme.qml"
        printf '%s' "$greeterConfigQml" > "$out/GreeterConfig.qml"
      '';
in
{
  options.claude-os.greeter.enable =
    lib.mkEnableOption "the Quickshell login greeter (replaces regreet)"
    // {
      description = ''
        Replace regreet with a Quickshell greeter reading the same generated
        Theme.qml as the bar.

        A broken QML file blanks the ENTIRE Quickshell config — in the greeter
        that means no way to log in. Load-check with the `quickshell_check` MCP
        tool (or `qs -p <dir>/shell.qml`) before enabling, keep the previous
        generation reachable in the boot menu, and remember greetd's agreety
        fallback on a VT.
      '';
    };

  config = lib.mkIf cfg.enable {
    # regreet and this module both write services.greetd.settings, so exactly
    # one may be on. mkForce rather than a plain `false`: regreet is enabled in
    # modules/desktop/hyprland.nix and both would otherwise be definitions of
    # the same option.
    services.displayManager.regreet.enable = lib.mkForce false;

    services.greetd = {
      enable = true;
      settings.default_session.command = lib.mkForce (
        lib.concatStringsSep " " [
          "${pkgs.dbus}/bin/dbus-run-session"
          # -s: allow VT switching (so ctrl+alt+F3 to a TTY still works if the
          # greeter misbehaves). -d: don't draw client decorations.
          "${pkgs.cage}/bin/cage -s -d --"
          "${pkgs.quickshell}/bin/quickshell -p ${greeterQml}/shell.qml"
        ]
      );
    };

    # The greeter user drives the GPU and reads input devices directly (regreet's
    # own module was arranging this for GTK; Quickshell needs it stated).
    users.users.greeter.extraGroups = [
      "video"
      "input"
    ];

    # Fonts must be present for the SYSTEM, not just the user profile — the
    # greeter runs before any user session, so it cannot see per-user fontconfig.
    fonts.packages = [
      (themeLib.fonts.sansSerif.package pkgs)
      (themeLib.fonts.monospace.package pkgs)
    ];
  };
}
